### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by gerrydoro** [MrUke/Scuolabook-downloader#2]
```
root@VMelementary:/home/gerardo/Documenti/Scuolabook-downloader-master# python download.py 
Your '_turner_session' key: ZHp5MHlJQThSd1ZuNU1FRWhGV3UvTkpqcWpVMGpsQXBmdEtmVk1BYTdkV0hGQ2hDRGZOaHdaU3RkSk5xSmJYWkN3Qnp1ZEt0UDY2OFFQYThaY0kwSS9hWWFXdnk5SUxKa3UrcStSVUw4ZmUrSlczUXZnNGx4Vmsvb3R5VlExNXh1OGJPU0FQUlB2SDJKRjlsNHhLT05TaTdSRlZzM2c4NmJDeHhTcG04UVBZQnJQOUNaM1drekY4MkZpK1YwUTQ2a1EvbUJNNDVLUjdJVXViZFlHaWVPTDZwQW1mSWlmZnRQdWZYRGhFbjR1OUo5Tk1od0wyZmpadmlaeHNZaElRKzhmV0M2V2RZL2xoRXJ6TkFyUmhnK0JodmJTVEp1M2JZZjFYbEdrSVNHSVNuWUROTUlKdWVVZG5Qa2hPRTdSNVpQWWdEVFlNMmluVDJ4eVJqaUN5WEJweXF6ek1uZWh6V1JTRlF0MkNKNEhxSmJwVTdiQVJRdzNKdG5yYUdmaW9CQ1ZFSTRXSXk4bzVJc1paV2s1THpKbjV6eWtzRlovcWZHbktDL3R1U093SS9aZHZxcTRnWkIveGxtS3RCZ0dMakNhNVhqS2JNRWx3b2tlSStrU0IzYzRQR29OUUJrMnZOWWw0WWd4SVdpRHlMelZYVVZmenhXWXJWRm9LQ1A4K3hWZkl3ak1YRmtBTEJDN1A1ckQ0QzhLc0U5elJPRXFCQ2s0OXZpR0ZQbTljdjdmbUpvV3pLdHFoeGVYR092b1g1NEtUdk1RSkFBKzJ6QWZnL3d6YW4rbEp0TG1VYWtYbWR2bFVzSWU1RllMSXhlYThlZWVYYjdMWW9uM2VRVFl0dS94SlZYbWxaaXRuZlVzYmllWDFudEJ4TTZ1MTVHclJxZThtV2VCaVljSG5VYmtTS0VnVTZMMDFMcW00VnQrWDloTStqcHV1Rk83MFY5ZnI3TGp2ODZWZWpNdDEvU0M2UWRWelRabFc5N1pzdmI5bXVGS1hRVTlNeHU0amtuTlNZaTJCdndoV3NzMmxadW5rTWN1aFJ2YlJUd1djNitaNDZmMUNNTmU4YXhuZy9TTzZDdVFwRktqV29zVmJuWVFjbldDRElwc3dlakxkcG5FeFJSMzltS0NQT0tpZThyd3NxMTU5aHpzRXRLb09YY1EvQkNDNm5wZEloSTB3dm52Rk51WWV1bGdJNFh1eVM2V0lWQkVkejdlRU1xK1FJN1AybFB3dXJqVytWTi8wPS0tMVZ4NUtPT2pCS2dmMVVuaHpyVmlMdz09--37674be974e101a9b271697fb763ee5a39f2ae2f

[Your library]

459)    TECNOLOGIE INFORMATICHE - RELEASE 2.0
1328)   LINGUAGGI WEB - LATO CLIENT
1931)   LINGUAGGI WEB - LATO SERVER E MOBILE COMPUTING
290)    Corso di informatica - Volume 1

Insert book ID to download: 1328
Traceback (most recent call last):
  File "download.py", line 32, in <module>
    title = re.search('"ws_title":"(.*?)"', data).group(1).encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'group'
root@VMelementary:/home/gerardo/Documenti/Scuolabook-downloader-master#
```

Provato con tutti e 4 gli ebook ma niente. È un mio problema o dell'app?

**Comment by ale00** [comment]
Alla linea 31 rimuovi `+ ".json"`

**Comment by gerrydoro** [comment]
Domani provo, grazie!

**Comment by gerrydoro** [comment]
`gerardo@VMelementary:~/Documenti/Scuolabook-downloader-master$ python download.py
Your '_turner_session' key: RHlPWHV3RXN2YStXZTJpZkJWNXkwTStNZitkSTVUSVM1L2tOd1RqMnlKVUUxSk5IemVrYWtzbFQrRU54V2ZHekxSUU9vQ2FKOTFWQXZ0VnpLSlkxMTUwYlRkckJHbnZJVHU5aVVIQlpzNWxUWk9xQ0Y3aXYyRkpnSlRqeDlQZXBlWTZjb01GMlJjV0pUQ1BtWTVhT1FJb1dVQk94UmYvcm5LaElYT1JJeFpKUkJ4M2orRWpnYVBmRWVYT0JwdVhHN01vQWhtZ1hmWmowMnlGOWh5b09rRU0ycUNzMktJcmZuSEd6YWdEandEMytLQTBDWnZUd1lSMC8xTEpzQ211MWpXM0c5TDd5d2xnbTRwSWNPdzF6TDEwdHlwdUhVSG4rSEFDTXhSY1ozckxDVml3VUs0RjNMS3AxZEd4M2JvY0JuNWJmQlFjTFpUNXo4QU5NSkt6ajZLTWVqclExOWpyN3pTMmdXMG83Q2V2cU43ZGJVRjI3Q01zMndVY1BlNm9UNE9aZ1UvRnlrSms2TUh5cEpuSVNnVDRHbUJPTFFEWVp4N2x5RTQ4MmF6UkZnL0o3ZVRNckM2T2NPMHJrN1oxVUhEVEtoeWdRS0NycFZDbW9GVEZUbmE3aDNWQjM3cTFqYktlRytwRGVnaTVvTFVBS010VkhDNFgyUDQwQkQ3MExkSm9Nd1JDWU1lbGg4WU92R1owRTdPRWtYT2VKRVhuRkM3VEorejhhQU1QRlhsM2hSdUtXN2JKZmE2YjFkU1RlZXZZUkUzRGYzWU9jMk02eWRUN1ZiWkRyTUY0bXpRbGJobko4RmJhTVZLL3NPUXBuZ0QzcFdCc1JwV2oyU21BbDhrSHlFaXhXUFRVRzYyU0pwWEFMTGgyYXJLT0pxKzIrcVJvMUtvWk5kRG9hTFNwTjJVWXBkVlUrTVNxVmVsYWdMWmxDOVIyWktSMjdkOVpwRE1VMEdMOE9QWWYzY1dneU1DOXBvbHJ2blFrb3pnM05Gai9peUgxeW9hWGUvVVR1ZjBYREVaMXpyV1hOYjhyYStpYnB3cVA3eldqRkZvbTgyOEtVV2pPUnc0Si95ZDR4cERmUEllQllpTUN2S1dsRW9zUnpVYWNkVDlrTDNwRWtSOHVOQlNyaW9oYXVvVUpFUE5EK2ZoOWZtdWdsWFdvMnFTdlI1Qi95ZWJjVjcxdXU4dDZSNzBza3lNWFRJNWRIeE42MGJONkdlZ2Zkc0xqaWJUemdUamJPUzRBPS0tMW5sdDJFR3c4M3NyalY5YXVLWnpzUT09--82e193c01c3f7e0a739015f9b4696365bd9f55a8

[Your library]

459)    TECNOLOGIE INFORMATICHE - RELEASE 2.0
1328)   LINGUAGGI WEB - LATO CLIENT
1931)   LINGUAGGI WEB - LATO SERVER E MOBILE COMPUTING
290)    Corso di informatica - Volume 1

Insert book ID to download: 1328

[Selected book]

Title: 'LINGUAGGI WEB - LATO CLIENT'
Author: A. Lorenzi, R. Giupponi, D. Iovino 
Publisher: Istituto Italiano Edizioni Atlas 
ISBN: 9788826891118 
Pages: 256 

Downloading page 1/256...Traceback (most recent call last):
  File "download.py", line 57, in <module>
    f.write(requests.get(link).content)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
gerardo@VMelementary:~/Documenti/Scuolabook-downloader-master$`

Questa volta è un'altro l'errore, ma il programma sembra essere andato più avanti di prima.

**Comment by ale00** [comment]
Sarebbe opportuno aprire un altro "Issue", comunque, passa tutto a Python 3, quindi se usi pip devi reinstallare le librerie con pip3

**Comment by gerrydoro** [comment]
Qui chiudo?

**Comment by ale00** [comment]
Si

**Comment by gerrydoro** [comment]
Ho rifatto tutto su Raspbian su rPi3 con pip3, ho rimosso il `+ ".json"` ma c'è ancora un errore
```
Downloading page 256/256...
Converting images to pdf format...
'1399a9906cd6351686e346d7d3a8a927.pdf' created!
Merging everything...
Traceback (most recent call last):
  File "download.py", line 77, in <module>
    merger.write(title + ".pdf")
TypeError: can't concat bytes to str
```

**Comment by gerrydoro** [comment]
Linea 79
`merger.write(title + ".pdf")`
va sostituita con
`merger.write(title.decode() + ".pdf")`
Oltre al precedente  `+ ".json"` da rimuovere alla linea 31

@ale00 ha una versione con già tutte le correzione, di cui magari **poteva farcene sapere l'esistenza!**
https://github.com/ale00/Scuolabook-Downloader-2
Chiudo.
