### ISSUE TITLE
f = open(cache + filename + ".jpg", "wb")

### ISSUE THREAD

**Issue by xFraz** [MrUke/Scuolabook-downloader#4]
Downloading page 1/480...Traceback (most recent call last):
  File "download.py", line 56, in <module>
    f = open(cache + filename + ".jpg", "wb")
IOError: [Errno 2] No such file or directory: '/tmp/7957ce936d1af81c6c20a8339b8a5c2c.jpg'

**Comment by gerrydoro** [comment]
Passa di qua, questa versione sembra essere obsoleta
https://github.com/ale00/Scuolabook-Downloader-2

**Comment by xFraz** [comment]
Grazie
