### ISSUE TITLE
Non va più

### ISSUE THREAD

**Issue by Pival81** [MrUke/Scuolabook-downloader#5]
Non va più.
Semplicemente dopo aver messo il valore del cookie non mi da nessun libro nella libreria, quando ne avrò almeno 5, e se provo a mettere l'id che trovo nell'url del webreader dal libro, mi da errore.

**Comment by gerrydoro** [comment]
Leggi i thread già aperti prima di crearne uno nuovo! E senza nessun dato come faccio a sapere che problema hai?
Comunque non sono io lo sviluppatore, ma credo che questa versione sia abbandonata.
Prova questa: https://github.com/ale00/Scuolabook-Downloader-2
